name: Publish Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-electron-windows:
    runs-on: windows-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: $(( ${{ github.event_name == 'pull_request' && github.event.pull_request.commits || 0 }} + 10 ))
      - name: Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build UI
        working-directory: .
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
        run: |
          $version=$(git describe)
          npm ci
          npm version -ws "$version"
          npm run app-package

          Compress-Archive -Path packages\insomnia\dist\win-unpacked\* -DestinationPath rest.ground-"$version".zip

      - name: Publish
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
            artifacts: "packages/insomnia/dist/*.exe,packages/insomnia/dist/squirrel-windows/*.exe,./*.zip"
            allowUpdates: true
            updateOnlyUnreleased: true

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |-
            packages/insomnia/dist/*.exe
            packages/insomnia/dist/squirrel-windows/*.exe
            ./*.zip

